[[language]]
name = "python"
language-servers = ["ruff", "pylsp", "basedpyright"]
formatter = { command = "ruff", args = ["format", "--line-length", "88", "-"] }
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.pylsp]
command = "pylsp"

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]
