* Emacs

All other configuration follows from Emacs, because Emacs the means by which Org
files are edited.

** Initialisation

MELPA is a package archive for Emacs.  Useful libraries are stored there.

#+BEGIN_SRC emacs-lisp :tangle emacs/init.el
  (require 'package)
  (add-to-list 'package-archives
	       '("melpa" . "https://melpa.org/packages/"))
  (package-initialize)
  (package-refresh-contents)
#+END_SRC

The ~use-package~ library adds a macro that provides a concise way to keep
configuration for external packages organised.  External packages are always be
downloaded if they are not found locally.n

#+BEGIN_SRC emacs-lisp :tangle emacs/init.el
  (unless (require 'use-package nil t)
    (package-install 'use-package))

  (eval-when-compile (require 'use-package))
  (require 'use-package-ensure)
  (setq use-package-always-ensure t)
#+END_SRC

** Global settings

Preferential global settings are configured next.  The documentation for all of
these settings is available in Emacs itself.

#+BEGIN_SRC emacs-lisp :tangle emacs/init.el
  (global-set-key [remap dabbrev-expand] 'hippie-expand)

  (global-visual-line-mode)
  (global-display-line-numbers-mode)
  (menu-bar-no-scroll-bar)
  (column-number-mode)
  (tool-bar-mode 0)
  (setq auto-save-default nil
	create-lockfiles nil
	make-backup-files nil

	display-line-numbers-type 'relative

	shift-select-mode nil

	tramp-default-method "ssh"

	apropos-sort-by-scores t)
#+END_SRC

It's useful to always delete trailing whitespace on save.

#+BEGIN_SRC emacs-lisp :tangle emacs/init.el
  (add-hook 'before-save-hook 'delete-trailing-whitespace)
#+END_SRC

A colour scheme and custom font adds familiarity.

#+BEGIN_SRC emacs-lisp :tangle emacs/init.el
  (use-package atom-one-dark-theme)
  (when (member "Inconsolata" (font-family-list))
    (set-frame-font "Inconsolata 13" nil t))
#+END_SRC

Some functions are disabled by default because they can be destructive.
Functions that have an understood purpose can be enabled.

#+BEGIN_SRC emacs-lisp :tangle emacs/init.el
  (put 'upcase-region 'disabled nil)
  (put 'downcase-region 'disabled nil)
#+END_SRC

On OS X at least, ~exec-path~ and the environment =PATH= variables are not
configured correctly.  Here they are set explicitly.

#+BEGIN_SRC emacs-lisp :tangle emacs/init.el
  (defun get-shell-path ()
    (seq-uniq
     (append
      exec-path
      (split-string
       (replace-regexp-in-string
	"[\t\s\n]+$"
	""
	(shell-command-to-string "$SHELL --login -c 'echo ${PATH}'"))
       ":"))))

  (setenv "PATH" (string-join (get-shell-path) ":"))
  (setq exec-path (get-shell-path))
#+END_SRC

** Global modes

These are modes would be useful in the vast majority of Emacs sessions.

*** Ido

Ido mode offers simple word-completion support.

#+BEGIN_SRC emacs-lisp :tangle emacs/init.el
  (ido-mode "both")
  (setq ido-enable-flex-matching t)
#+END_SRC

*** Flyspell

Flyspell offers real time spell-checking in buffers.

#+BEGIN_SRC emacs-lisp :tangle emacs/init.el
  (setq ispell-program-name "aspell")
#+END_SRC

*** Windmove

Windmove enables granular movement among windows.

#+BEGIN_SRC emacs-lisp :tangle emacs/init.el
  (windmove-default-keybindings)
  (global-set-key (kbd "C-x w k") 'windmove-up)
  (global-set-key (kbd "C-x w j") 'windmove-down)
  (global-set-key (kbd "C-x w h") 'windmove-left)
  (global-set-key (kbd "C-x w l") 'windmove-right)
#+END_SRC

*** Magit

Magit provides an interface with Git.  The keybinding for interfacing with the
built-in Emacs version control system is overridden because Magit supersedes its
functionality.

#+BEGIN_SRC emacs-lisp :tangle emacs/init.el
  (use-package magit
    :bind ("C-x v" . magit-status))
#+END_SRC

** Language modes

Most language-specific major modes are provided by third parties, but some are
included with Emacs.  Both kinds are configured here.

*** Org mode

Org mode is the literate programming environment this document is written in.
It's already included in Emacs but it can be enhanced with some further
configuration.

#+BEGIN_SRC emacs-lisp :tangle emacs/init.el
  (add-hook 'org-mode-hook
	    (lambda ()
	      (abbrev-mode)
	      (auto-fill-mode)
	      (flyspell-mode)
	      (setq fill-column 80)))
#+END_SRC

A function to go to the next heading whilst narrowing is in effect is defined to
make an Org file feel more akin to an Info one.

#+BEGIN_SRC emacs-lisp :tangle emacs/init.el
  (defun org-next-heading-node ()
    "Move to the next heading node while narrowed."
    (interactive)
    (widen)
    (forward-char 1)
    (if (search-forward-regexp "^\*+" (point-max) t)
	(progn
	  (forward-line 0)
	  (org-narrow-to-subtree)
	  (org-content)
	  (org-show-entry))))
#+END_SRC

A similar one is defined to go to the previous heading.

#+BEGIN_SRC emacs-lisp :tangle emacs/init.el
  (defun org-prev-heading-node ()
    "Move to the previous heading node while narrowed."
    (interactive)
    (org-narrow-to-subtree)
    (goto-char (point-min))
    (widen)
    (if (search-backward-regexp "^\*+" (point-min) t)
	(progn
	  (forward-line 0)
	  (org-narrow-to-subtree)
	  (org-content)
	  (org-show-entry))
      (progn
	(org-overview)
	(goto-char (point-min)))))
#+END_SRC

Keybindings should be defined to easily execute both of these functions.

#+BEGIN_SRC emacs-lisp :tangle emacs/init.el
  (add-hook 'org-mode-hook
	    (lambda ()
	      (local-set-key (kbd "C-c n") 'org-next-heading-node)
	      (local-set-key (kbd "C-c p") 'org-prev-heading-node)))
#+END_SRC

When exporting to \LaTeX, it's useful to have some common packages already
included.  Minted is used to highlight source code snippets.

#+BEGIN_SRC emacs-lisp :tangle emacs/init.el
  (add-to-list 'org-latex-packages-alist '("" "minted"))
  (let ((pdf-cmd (concat "%latex " "-shell-escape "
			 "-interaction " "nonstopmod "
			 "-output-directory " "%o " "%f")))
    (setq org-latex-listings 'minted
	  org-latex-pdf-process (list pdf-cmd pdf-cmd pdf-cmd)))
#+END_SRC

The ~xcolor~ package enables additional colours to be used in text.

#+BEGIN_SRC emacs-lisp :tangle emacs/init.el
  (add-to-list 'org-latex-packages-alist '("dvipsnames" "xcolor"))
#+END_SRC
