* Emacs

All other configuration follows from Emacs, because Emacs the means by
which Org files are edited.

** Initialisation

MELPA is a package archive for Emacs.  Useful libraries are stored there.

#+BEGIN_SRC emacs-lisp :tangle emacs/init.el
  (require 'package)
  (add-to-list 'package-archives
	       '("melpa" . "https://melpa.org/packages/"))
  (package-initialize)
  (package-refresh-contents)
#+END_SRC

The ~use-package~ library adds a macro that provides a concise way to
keep configuration for external packages organised.  External packages
are always be downloaded if they are are not found locally.n

#+BEGIN_SRC emacs-lisp :tangle emacs/init.el
  (unless (require 'use-package nil t)
    (package-install 'use-package))

  (eval-when-compile (require 'use-package))
  (require 'use-package-ensure)
  (setq use-package-always-ensure t)
#+END_SRC

** Global settings

Preferential global settings are configured next. The documentation
for all of these settings is available in Emacs itself.

#+BEGIN_SRC emacs-lisp :tangle emacs/init.el
  (global-display-line-numbers-mode)
  (menu-bar-no-scroll-bar)
  (column-number-mode)
  (tool-bar-mode 0)
  (setq auto-save-default nil
	create-lockfiles nil
	make-backup-files nil

	display-line-numbers-type 'relative

	shift-select-mode nil

	apropos-sort-by-scores t)
#+END_SRC

It's useful to always delete trailing whitespace on save.

#+BEGIN_SRC emacs-lisp :tangle emacs/init.el
  (add-hook 'before-save-hook 'delete-trailing-whitespace)
#+END_SRC

A colour scheme adds familiarity.

#+BEGIN_SRC emacs-lisp :tangle emacs/init.el
  (use-package atom-one-dark-theme)
#+END_SRC

** Global modes

These are modes would be useful in the vast majority of Emacs
sessions.

*** Magit

Magit provides an interface with Git. The keybinding for interfacing
with the built-in Emacs version control system is overridden because
Magit supersedes its functionality.

#+BEGIN_SRC emacs-lisp :tangle emacs/init.el
  (use-package magit
    :bind ("C-x v" . magit-status))
#+END_SRC
