* Bootstrap

Script to bootstrap.

#+begin_src bash :tangle init.sh
if [ ! -f "${HOME}/.emacs.d/init.el" ]; then
    ln -s "${PWD}/emacs/init.el" "${HOME}/.emacs.d/init.el"
fi

if [ ! -f "${HOME}/.elisp-locals.el" ]; then
    echo "Ensure you populate ${HOME}/.elisp-locals.el with sane values"
    echo '(setq my/secrets-directory ""' >> "${HOME}/.elisp-locals.el"
    echo '      my/ledger-directory "")' >> "${HOME}/.elisp-locals.el"
fi
#+end_src

* Emacs
  :PROPERTIES:
  :header-args: :tangle emacs/init.el
  :END:

All other configuration follows from Emacs, because Emacs is the means by which
Org files are edited.

** Initialization

MELPA is a package archive for Emacs.  Useful libraries are stored there.

#+begin_src emacs-lisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/") t)
(package-initialize)
(package-refresh-contents)
#+end_src

The ~use-package~ library adds a macro that provides a concise way to keep
configuration for external packages organised.  External packages will always be
downloaded if they are not found locally.

#+begin_src emacs-lisp
(unless (require 'use-package nil t)
(package-install 'use-package))

(eval-when-compile (require 'use-package))
(require 'use-package-ensure)
(setq use-package-always-ensure t)
#+end_src

Set host dependant variable definitions.

#+begin_src emacs-lisp
(load "~/.elisp-locals.el")
#+end_src

** Global settings
Preferential global settings are configured next.  The documentation for all of
these settings is available in Emacs itself.

#+begin_src emacs-lisp
(global-set-key [remap dabbrev-expand] 'hippie-expand)

(global-visual-line-mode)
(global-display-line-numbers-mode)
(menu-bar-no-scroll-bar)
(column-number-mode)
(tool-bar-mode 0)

(setq-default indent-tabs-mode nil
	      line-spacing 2)

(setq auto-save-default nil
      create-lockfiles nil
      make-backup-files nil
      display-line-numbers-type 'relative
      shift-select-mode nil
      tramp-default-method "ssh"
      apropos-sort-by-scores t)
#+end_src

It's useful to always delete trailing whitespace on save.

#+begin_src emacs-lisp
(add-hook 'before-save-hook 'delete-trailing-whitespace)
#+end_src

A colour scheme and custom font adds familiarity.

#+begin_src emacs-lisp
(use-package atom-one-dark-theme
  :init
  (load-theme 'atom-one-dark t))
(when (member "Monaco" (font-family-list))
  (set-frame-font "Monaco 12" nil t))
#+end_src

Some functions are disabled by default because they can be destructive.
Functions that have an understood purpose can be enabled.

#+begin_src emacs-lisp
(put 'upcase-region 'disabled nil)
(put 'downcase-region 'disabled nil)
#+end_src

On OS X at least, ~exec-path~ and the environment =PATH= variables are not
configured correctly.  Here they are set explicitly.

#+begin_src emacs-lisp
(defun get-shell-path ()
  (seq-uniq
   (append
    exec-path
    (split-string
     (replace-regexp-in-string
      "[\t\s\n]+$"
      ""
      (shell-command-to-string "$SHELL --login -c 'echo ${PATH}'"))
     ":"))))

(require 'subr-x)
(setenv "PATH" (string-join (get-shell-path) ":"))
(setq exec-path (get-shell-path))
#+end_src

** Mode Line

#+begin_src emacs-lisp :results value silent
(setq-default mode-line-format
	      (list "%e"
		    '(:eval (propertize " " 'face '(:height 164)))
		    '(:eval (propertize "%m" 'face '(:foreground "#00FFFF" :height 100)))
		    '(:eval (propertize " • " 'face '(:foreground "#FFFF00")))
		    '(:eval (propertize "%b" 'face 'font-lock-text-face))
		    '(:eval (let* ((git-branch (propertize (shell-command-to-string
							    "git rev-parse --abbrev-ref HEAD 2> /dev/null | tr -d '\n'")
							   'face '(:foreground "yellow")))
				   (pos (concat "["
						(propertize (format-mode-line "%03l")
							    'face '(:foreground "#228B22"))
						","
						(propertize (format-mode-line "%03C")
							    'face '(:foreground "#226B22"))
						"]"))
				   (right-length (+ (length git-branch)
						    (length pos)
						    3)))
			      (list (propertize " "
						'display `((space
							    :align-to (- (+ right right-fringe right-margin)
									 ,right-length))))
				    git-branch " "
				    pos)))))
#+end_src

** Global modes

These are modes would be useful in the vast majority of Emacs sessions.

*** Ido

Ido mode offers simple word-completion support.

#+begin_src emacs-lisp
(ido-mode "both")
(setq ido-enable-flex-matching t)
#+end_src

*** Flyspell

Flyspell offers real time spell-checking in buffers.

#+begin_src emacs-lisp
(setq ispell-program-name "aspell")
#+end_src

*** Windmove

Windmove enables granular movement among windows.

#+begin_src emacs-lisp
(windmove-default-keybindings)
(global-set-key (kbd "C-x w k") 'windmove-up)
(global-set-key (kbd "C-x w j") 'windmove-down)
(global-set-key (kbd "C-x w h") 'windmove-left)
(global-set-key (kbd "C-x w l") 'windmove-right)
#+end_src

*** Magit

Magit provides an interface with Git.  The keybinding for interfacing with the
built-in Emacs version control system is overridden because Magit supersedes its
functionality.

#+begin_src emacs-lisp
(use-package magit
  :bind ("C-x v" . magit-status))

(add-hook 'git-commit-setup-hook 'git-commit-turn-on-flyspell)
#+end_src

*** Helm
#+begin_src emacs-lisp
(use-package helm
  :init
  (require 'helm-config))
#+end_src

*** Projectile
#+begin_src emacs-lisp
(use-package projectile
  :init
  (projectile-mode +1)
  :bind
  ("C-S-c p" . projectile-command-map))
#+end_src

*** Ivy, Counsel and Swiper
#+begin_src emacs-lisp
(use-package counsel
  :init
  (ivy-mode 1)
  :bind
  ("C-x b" . ivy-switch-buffer)
  ("M-x" . counsel-M-x)
  ("C-x C-f" . counsel-find-file)
  ("M-y" . counsel-yank-pop)
  ("C-s" . swiper-isearch)
  :config
  (setq ivy-use-virtual-buffers t
        ivy-count-format "(%d/%d) "))
#+end_src

*** Treemacs
#+begin_src emacs-lisp
(use-package treemacs
  :config
  (treemacs-follow-mode t)
  (treemacs-resize-icons 14))
(use-package treemacs-projectile
  :after treemacs projectile)
#+end_src

** Language modes

Most language-specific major modes are provided by third parties, but some are
included with Emacs.  Both kinds are configured here.

#+begin_src emacs-lisp
(use-package lsp-mode
  :bind ("C-c x d" . lsp-find-definition)
  :bind ("C-c x r" . lsp-find-references)
  :config (setq lsp-prefer-flymake nil
                lsp-enable-snippet t))

(use-package lsp-ui)

(use-package company-lsp
  :init (setq company-idle-delay 0.1))

(use-package yasnippet)
#+end_src

#+begin_src emacs-lisp
(use-package flycheck
  :init (global-flycheck-mode))
#+end_src

*** Org mode

Org mode is the literate programming environment this document is written in.
It's already included in Emacs but it can be enhanced with some further
configuration.

Some values must be set before Org mode is even loaded.

#+begin_src emacs-lisp
(use-package org)
(when (version<= "9.2" (org-version))
  (require 'org-tempo))

  (setq org-enforce-todo-checkbox-dependencies t
	org-enforce-todo-dependencies t
	org-todo-keywords '((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d)")
			    (sequence "WAIT(w@/!)" "|" "CANC(c@/!)")))
#+end_src

And some are useful in every mode.

#+begin_src emacs-lisp
(global-set-key (kbd "C-c a") 'org-agenda)
#+end_src

However, most values are set upon entering an Org buffer.

#+begin_src emacs-lisp
(add-hook 'org-mode-hook
	  (lambda ()
#+end_src

Helpful minor modes are enabled.

#+begin_src emacs-lisp
(abbrev-mode)
(auto-fill-mode)
(flyspell-mode)
#+end_src

Agenda files are read from an explicit directory, removing the need for these
keybindings.

#+begin_src emacs-lisp
(local-unset-key (kbd "C-c ["))
(local-unset-key (kbd "C-c ]"))
#+end_src

The document width is set to something that I find more manageable.

#+begin_src emacs-lisp
(setq fill-column 80
#+end_src

Dropbox is used to sync Org files with Orgzly on Android.

#+begin_src emacs-lisp
org-agenda-files '("~/Dropbox/org")
#+end_src

This sets preferential faces for states.

#+begin_src emacs-lisp
org-todo-keyword-faces '(("TODO" :foreground "moccasin" :weight bold)
			 ("NEXT" :foreground "cyan" :weight bold)
			 ("DONE" :foreground "green" :weight bold)
			 ("WAIT" :foreground "orange" :weight bold)
			 ("CANC" :foreground "rosy brown" :weight bold :strike-through t))
#+end_src

Default tags are set.

#+begin_src emacs-lisp
org-tags-alist '(("@home" . ?h) ("@laptop" . ?l) ("book" . ?b))
#+end_src

This enables preferential behaviour for states and transition logging.

#+begin_src emacs-lisp
org-use-fast-todo-selection 'prefix
org-treat-S-cursor-todo-selection-as-state-change nil
org-log-done 'time
org-log-into-drawer t
#+end_src

Source blocks have font locking enabled and editing is done in the current
window.

#+begin_src emacs-lisp
org-src-preserve-indentation t
org-src-window-setup 'current-window
#+end_src

#+begin_src emacs-lisp
org-confirm-babel-evaluate
(lambda (language body)
  (if (equal language "haskell")
      nil
    t))
#+end_src

And finally, recommended key configurations are included.

#+begin_src emacs-lisp
org-special-ctrl-a/e t
org-special-ctrl-k t
org-ctrl-k-protect-subtree 'error))) 	; Closes org-mode-hook lambda
#+end_src

A helper function is used to automatically complete parent TODO items.

#+begin_src emacs-lisp
(defun org-summary-todo (number-done number-not-done)
  "Switch entry to DONE when all subentries are done."
  (when (= number-not-done 0) (org-todo 'done)))
(add-hook 'org-after-todo-statistics-hook 'org-summary-todo)
#+end_src

The list of languages to support code execution in source blocks is updated.

#+begin_src emacs-lisp
(org-babel-do-load-languages
 'org-babel-load-languages
 '((emacs-lisp . t)
   (ledger . t)))
#+end_src

A function to go to the next heading whilst narrowing is in effect is defined to
make an Org buffer feel more akin to an Info one.

#+begin_src emacs-lisp
(defun org-next-heading-node ()
  "Move to the next heading node while narrowed."
  (interactive)
  (widen)
  (forward-char 1)
  (if (search-forward-regexp "^\*+" (point-max) t)
      (progn
	(forward-line 0)
	(org-narrow-to-subtree)
	(org-content)
	(org-show-entry))))
#+end_src

A similar one is defined to go to the previous heading.

#+begin_src emacs-lisp
(defun org-prev-heading-node ()
  "Move to the previous heading node while narrowed."
  (interactive)
  (org-narrow-to-subtree)
  (goto-char (point-min))
  (widen)
  (if (search-backward-regexp "^\*+" (point-min) t)
      (progn
	(forward-line 0)
	(org-narrow-to-subtree)
	(org-content)
	(org-show-entry))
    (progn
      (org-overview)
      (goto-char (point-min)))))
#+end_src

Keybindings should be defined to easily execute both of these functions.

#+begin_src emacs-lisp
(add-hook 'org-mode-hook
	  (lambda ()
	    (local-set-key (kbd "C-c n") 'org-next-heading-node)
	    (local-set-key (kbd "C-c p") 'org-prev-heading-node)))
#+end_src

When exporting to \LaTeX, it's useful to have some common packages already
included.  Minted is used to highlight source code snippets.  The ~xcolor~
package enables additional colours to be used in text.

#+begin_src emacs-lisp
(let ((pdf-cmd (concat "%latex " "-shell-escape "
		       "-interaction " "nonstopmod "
		       "-output-directory " "%o " "%f")))
  (setq org-latex-listings 'minted
	org-latex-pdf-process (list pdf-cmd pdf-cmd pdf-cmd)))

(add-hook 'org-mode-hook
	  (lambda ()
	    (add-to-list 'org-latex-packages-alist
			 '("" "minted"))
	    (add-to-list 'org-latex-packages-alist
			 '("dvipsnames" "xcolor"))))
#+end_src

Ox is used for blogging with Hugo.

#+begin_src emacs-lisp
(use-package ox-hugo
  :after ox)
#+end_src

I use specific format when writing a gratitude journal.  This function creates a
template for it.

#+begin_src emacs-lisp
(defun org-journal-insert-entry-template (thought)
  "Insert a new journal entry with a provided THOUGHT."
  (interactive "sWhat's on your mind? ")
  (let ((fname (format-time-string "%F")))
    (insert (concat "** " thought "\n"))
    (insert "    :PROPERTIES:\n")
    (insert (concat "    :EXPORT_DATE: " fname "\n"))
    (insert (concat "    :EXPORT_FILE_NAME: " fname "\n"))
    (insert "    :END:\n#+HUGO:MORE\n\n")
    (save-mark-and-excursion
      (forward-line -6)
      (org-cycle-hide-drawers 'children))
    (insert "*I am grateful for:*\n1. ")
    (save-mark-and-excursion
      (insert "\n1.\n1.\n\n")
      (insert "*What would make today great?*\n1.\n1.\n1.\n\n")
      (insert "*Daily affirmation: I am...*\n\n")
      (insert "*What made today amazing?*\n1.\n1.\n1.\n\n")
      (insert "*What did Jade do that I'm appreciative of?*\n1.\n\n")
      (insert "*What did my parents do that I'm appreciative of?*\n1.\n\n")
      (insert "*How could I have made today better?*\n\n"))))
#+end_src

#+begin_src emacs-lisp
(use-package org-roam
  :config
  (make-directory "~/commonplace" t)
  (setq org-roam-directory "~/commonplace")
  (add-hook 'after-init-hook 'org-roam-mode))

(use-package org-ref
  :config
  (setq reftex-default-bibliography '("~/commonplace/references.bib")
  org-ref-bibliography-notes "~/commonplace/notes.org"
  org-ref-default-bibliography '("~/commonplace/references.bib")
  org-ref-pdf-directory "~/commonplace/bibtex-pdfs/"))
#+end_src

*** Rust

Rust font locking is provided by ~rust-mode~.  The major mode also interfaces
with ~rustfmt~ so that the tool is ran on save.

#+begin_src emacs-lisp
(use-package rust-mode
  :init (setq rust-format-on-save t)
  :hook
  (rust-mode . subword-mode)
  (rust-mode . lsp))
#+end_src

Interacting with Cargo is better provided with the ~cargo-minor-mode~ package.

#+begin_src emacs-lisp
(use-package cargo
  :hook (rust-mode . cargo-minor-mode))
#+end_src

*** Scala

#+begin_src emacs-lisp
(use-package scala-mode
  :hook (scala-mode . lsp)
  :mode "\\.s\\(cala\\|bt\\)$")

(add-hook 'scala-mode-hook
	  (lambda ()
	    (add-hook 'before-save-hook 'lsp-format-buffer nil 'local)))
#+end_src

*** Haskell
#+begin_src emacs-lisp
(use-package haskell-mode)
#+end_src

*** Erlang
#+begin_src emacs-lisp
(use-package erlang)
#+end_src

*** YAML
#+begin_src emacs-lisp
(use-package yaml-mode)
#+end_src

*** Jq
#+begin_src emacs-lisp
(use-package jq-mode)
#+end_src

*** Ledger
Emacs is well-suited for manipulating ledger files.

#+begin_src emacs-lisp
(setq ledger-binary-path "hledger")
(use-package ledger-mode)

(add-to-list 'load-path "~/.emacs.d/lisp")
(require 'beancount)
#+end_src

*** PDF

Viewing PDF documents inside Emacs removes the need for another tool.

#+begin_src emacs-lisp
(use-package pdf-tools
  :init
  (pdf-tools-install))
#+end_src

* Commands
** Weight log
To facilitate daily logging of one's weight.

#+begin_src emacs-lisp :tangle emacs/init.el
(defun my/log-weight (weight)
  "Logs a WEIGHT value.

This function should be invoked at most once per day.  When
invoked more frequently, the WEIGHT value provided will be
discarded.

In addition to logging weight, this function will commit the
changes to a git repository and push the changes to its
configured remote."
  (interactive "nWeight: ")
  (let ((buffer (find-file-noselect (format "%s/weight_log.csv" my/secrets-directory))))
    (priv/log-weight-to-buffer weight buffer)
    (with-current-buffer buffer
      (set (make-local-variable 'save-silently) t)
      (save-buffer)
      (call-process "git" nil nil nil "commit" "./weight_log.csv" "-m" "Update weight log")
      (call-process "git" nil nil nil "push"))))

(defun priv/log-weight-to-buffer (weight buffer)
  "Logs a WEIGHT value to a BUFFER."
  (with-current-buffer
      buffer
    (let* ((current-date (format-time-string "%Y-%m-%d"))
           (last-line-end-pos (if (save-excursion
                                    (goto-char (point-max))
                                    (eq (progn (forward-line 0) (point)) (point-max)))
                                  (1- (point-max))
                                (point-max)))
           (last-date (car (split-string (buffer-substring (save-excursion
                                                             (goto-char last-line-end-pos)
                                                             (forward-line 0)
                                                             (point))
                                                           last-line-end-pos)
                                         ","))))
      (message "%s %s" last-line-end-pos last-date)
      (if (string> current-date last-date)
          (progn
            (goto-char last-line-end-pos)
            (insert (format "\n%s,%s\n" current-date weight)))
        (message "Skipping - last log entry (on %s) is not in the past" last-date)))))

(ert-deftest my-test/log-weight-to-buffer ()
  "Tests logging weight values to a buffer."
  (with-temp-buffer
    (insert "2020-01-01,75.0")
    (priv/log-weight-to-buffer 76.0 (buffer-name))
    (should (equal (buffer-string)
                   (format "2020-01-01,75.0\n%s,76.0\n"
                           (format-time-string "%Y-%m-%d"))))

    (erase-buffer)
    (insert "2100-01-01,75.0\n")
    (priv/log-weight-to-buffer 76.0 (buffer-name))
    (should (equal (buffer-string) "2100-01-01,75.0\n"))))
#+end_src

** Fava session
Fava is a graphical display for beancount ledgers.  This command starts a Fava
process if one isn't running already, and then displays it in a browser.

#+begin_src emacs-lisp :tangle emacs/init.el
(defun my/fava ()
  "Opens Fava."
  (interactive)
  (unless (get-process "fava")
    (let ((buffer (get-buffer-create "*fava*")))
      (with-current-buffer buffer
        (setq default-directory my/ledger-directory)
        (start-process "fava" buffer "fava" "./beancount.ledger"))))
  (with-current-buffer (get-buffer "*fava*")
    (save-excursion
      (goto-char 0)
      (search-forward-regexp "Running Fava on \\(http://localhost:[0-9]+\\)")
      (browse-url (match-string 1)))))
#+end_src
