# Rebind prefix
set-option -g prefix C-q
bind-key C-q send-prefix
unbind-key C-b

# Alter delay when sending commands
set-option -sg escape-time 1

# set window and pane indexes to start at '1'
set-option -g base-index 1
set-window-option -g pane-base-index 1

# Reload tmux.conf in the current session
bind-key r source-file ~/.tmux.conf \; display-message "Reloaded!"

# Rebind pane splitters
bind-key v split-window -h
bind-key s split-window -v
# unbind-key "
bind-key % choose-tree # replace later

# Rebind pane movement
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Bind pane resizing
bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5

unbind-key Left
unbind-key Right
unbind-key Down
bind-key Up last-window # replace later

# Rebind window movement
bind-key -r C-j select-window -t :-
bind-key -r C-k select-window -t :+

# Disable mouse mode
set-window-option -g mode-mouse off

# Enable 256-color mode
set-option -g default-terminal "screen-256color"

# Set colors
set-option -g status-fg colour244
set-option -g status-bg default

set-window-option -g window-status-fg colour238
set-window-option -g window-status-bg default
set-window-option -g window-status-attr dim
set-window-option -g window-status-current-fg colour250
set-window-option -g window-status-current-bg default
set-window-option -g window-status-current-attr bright

set-option -g pane-border-fg colour236
set-option -g pane-active-border-fg colour247

set-option -g message-fg colour244
set-option -g message-bg default
set-option -g message-attr bright

# Set status bar formtat
set-option -g status-left-length 40
set-option -g status-left "#[fg=colour028]#S#[fg=colour069] ❯ "
set-option -g status-right "#[fg=colour027]%R #[fg=colour069]❮ #[fg=colour136]%d %B, %Y"
set-option -g window-status-format " #W "
set-option -g window-status-current-format " #W "

# Enable UTF-8 support
set-option -g status-utf8 on

# Set status bar refresh interval
set-option -g status-interval 20

# Monitor activity in all windows
set-option -g monitor-activity on
set-option -g visual-activity on

# Enable vi mode
set-window-option -g mode-keys vi

# Set vi-like copy mode bindings
bind-key C-[ copy-mode
unbind-key p
bind-key p paste-buffer
bind-key -t vi-copy 'v' begin-selection
bind-key -t vi-copy 'y' copy-pipe "reattach-to-user-namespace pbcopy"
unbind-key [
